### ISSUE TITLE
Any instructions?

### ISSUE THREAD

**Issue by cdevent** [wandersher/ASUS-FX553-MacOS#1]
Can you please provide some instructions how to run macos on that laptop?
What's best BIOS configurations,
how to create installation disk, etc..

P.S. Also many thanks that you're sharing this code! You're awesome!

**Comment by wandersher** [comment]
No, i not help everyone install macos on his laptop, i only share my own config.
Youtube has a bilion videos how to install macos on pc, just try some search.
